"use server";

import { authorize } from "@/lib/actions/admin/core";

export type FaqItem = {
  id: string;
  category: string;
  question: string;
  answer: string;
};

export async function askWebsiteAiChatbotAction(
  userMessage: string,
  faqs: FaqItem[],
  personality = "Friendly Host"
): Promise<{ ok: boolean; reply?: string; error?: string }> {
  const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
  if (!GEMINI_API_KEY) {
    return { ok: false, error: "GEMINI_API_KEY is not configured in .env.local" };
  }

  const faqText = faqs.length > 0
    ? faqs.map((f) => `Q: ${f.question}\nA: ${f.answer}`).join("\n\n")
    : "Standard Rules: Minimum deposit is $5.00 via CashApp/Venmo/PayPal. Cashouts take 5-15 mins 24/7. Games include Juwa 777, Orion Stars, FireKirin, GameVault.";

  const prompt = `
You are a warm, helpful, intelligent human customer support representative at Spinora Casino.

Your Personality: ${personality}
- Act completely natural, friendly, and human-like.
- Genuinely understand the user's intent, tone, typos, and feelings.
- Answer accurately based on our casino knowledge base below, but present it conversationally (do not copy-paste robotic text).
- Keep responses concise (2 to 4 sentences max), clear, and reassuring.

Casino Knowledge Base & Active FAQs:
${faqText}

Customer Message: "${userMessage}"

Respond naturally as the human casino host:
`;

  try {
    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
        }),
      }
    );

    const data = await res.json();
    const reply = data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();

    if (!reply) {
      return { ok: false, error: "No response generated by AI." };
    }

    return { ok: true, reply };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Error querying AI engine.";
    return { ok: false, error: msg };
  }
}

export async function generateWebsiteFaqsAction(): Promise<{
  ok: boolean;
  faqs?: FaqItem[];
  error?: string;
}> {
  const auth = await authorize("cms.manage");
  if ("error" in auth && process.env.NODE_ENV !== "development") {
    return { ok: false, error: auth.error };
  }

  const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
  if (!GEMINI_API_KEY) {
    return { ok: false, error: "GEMINI_API_KEY is not configured in .env.local" };
  }

  const prompt = `
You are a senior customer experience manager for Spinora Casino, a premium online social sweeps & arcade gaming platform.

Website Key Features & Rules:
- Cashout Speed: Fast payouts in 5-15 minutes via CashApp, Venmo, PayPal, and Zelle.
- Minimum Deposit: $5.00 minimum deposit across all payment apps.
- Supported Games: Juwa 777, Orion Stars, GameVault, Cosmic Arcade, Dragon City, FireKirin, SweepsRoyal.
- Daily Bonuses: 50% deposit match bonus daily, daily spin wheel, streak rewards, and free play credits.
- Security & Support: 24/7 live support, instant automated account creation, bank email verification.

Task:
Generate 6 highly practical, human-like Customer FAQs (Questions & Answers) specifically customized for Spinora Casino website players.

Output MUST be strict raw JSON array of objects with keys: "category", "question", "answer".
Example output format:
[
  {
    "category": "Cashouts",
    "question": "How long do cashout payouts take?",
    "answer": "Cashout requests are reviewed and sent via CashApp, Venmo, or PayPal within 5 to 15 minutes max! Our cashier team operates 24/7."
  }
]
`;

  try {
    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
        }),
      }
    );

    const data = await res.json();
    const rawText = data?.candidates?.[0]?.content?.parts?.[0]?.text ?? "[]";
    const jsonStr = rawText.replace(/```json\s*/gi, "").replace(/```/g, "").trim();
    const parsed = JSON.parse(jsonStr) as Array<{ category: string; question: string; answer: string }>;

    const faqs: FaqItem[] = parsed.map((item, idx) => ({
      id: `ai-${Date.now()}-${idx}`,
      category: item.category || "General",
      question: item.question,
      answer: item.answer,
    }));

    return { ok: true, faqs };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Failed to generate FAQs via Gemini AI.";
    return { ok: false, error: message };
  }
}
